import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Sidebar } from "../components/Sidebar/Sidebar";
import { Navbar } from "../components/Navbar/Navbar";


const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Virtual Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-dark-primary text-text ${poppins.className}`}>
        <div className="flex">
          <div>
            <Sidebar />
          </div>
          <div className="w-9/12 mx-24 gap-5">
            <Navbar />
            {children}
            </div>
        </div>
      </body>
    </html>
  );
}
